ADJECTIVES = [
    "admiring", "adoring", "affectionate", "agitated", "amazing", "angry",
    "awesome", "blissful", "boring", "brave", "clever", "cocky",
    "compassionate", "competent", "condescending", "confident",
    "cranky", "dazzling", "determined", "distracted", "dreamy", "eager",
    "ecstatic", "elastic", "elated", "elegant", "eloquent", "epic",
    "fervent", "festive", "flamboyant", "focused", "friendly", "frosty",
    "gallant", "gifted", "goofy", "gracious", "happy", "hardcore",
    "heuristic", "hopeful", "hungry", "infallible", "inspiring", "jolly",
    "jovial", "keen", "kind", "laughing", "loving", "lucid", "mystifying",
    "modest", "musing", "naughty", "nervous", "nifty", "nostalgic",
    "objective", "optimistic", "peaceful", "pedantic", "pensive", "practical",
    "priceless", "quirky", "quizzical", "relaxed", "reverent", "romantic",
    "sad", "serene", "sharp", "silly", "sleepy", "stoic", "stupefied",
    "suspicious", "tender", "thirsty", "trusting", "unruffled", "upbeat",
    "vibrant", "vigilant", "vigorous", "wizardly", "wonderful",
    "xenodochial", "youthful", "zealous", "zen"
]

ORC_NAMES = [
    'Gludbog', 'Ulgha', 'Kubguk', 'Duugh', 'Tobdakh', 'Zugrak', 'Drutrug',
    'Thokgor', 'Zikgor', 'Bugrog', 'Brughnab', 'Mashnakh', 'Sugugh',
    'Bludmuk', 'Sagdakh', 'Skagblug', 'Thughnab', 'Odbog', 'Ruglut', 'Grurk',
    'Garzug', 'Drurk', 'Hubbag', 'Brubbag', 'Glagha', 'Sulgob', 'Mubmak',
    'Igugh', 'Trobmag', 'Oznag', 'Durgash', 'Kukpug', 'Blokpug', 'Snuzdush',
    'Nugrog', 'Nozdakh', 'Ubgorg', 'Kratruk', 'Krorgash', 'Guzgub', 'Blulbug',
    'Muzrub', 'Trogburz', 'Skurduk', 'Sobkog', 'Bakduh', 'Tromburz',
    'Ghudhagh', 'Smimbub', 'Ubmak', 'Ogdush', 'Kulbulg', 'Thorg', 'Ubgug',
    'Hulbog', 'Umdush', 'Murghud', 'Thugdugh', 'Bulgug', 'Smibzagh', 'Idkush',
    'Kuzdush', 'Marthug', 'Nabzagh', 'Nuzhug', 'Bugbu', 'Bligmub', 'Brulbag',
    'Goshog', 'Mulurg', 'Smudbagh', 'Gradgig', 'Thrazgash', 'Zuzg', 'Rulgha',
    'Kuggug', 'Muzg', 'Ghukpug', 'Kubgu', 'Ubgu', 'Ugzag', 'Ulurg', 'Dobdug',
    'Thulbag', 'Skubdakh', 'Rugrurg', 'Ughbub', 'Marg', 'Zamburz', 'Moghnab',
    'Thushzog', 'Sogrunk', 'Blazrub', 'Ogug', 'Blodak', 'Smuzhug', 'Glurdag',
    'Thorbosh', 'Noknug', 'Throlbulg', 'Sugburz', 'Agugh', 'Rukduh', 'Glodkuh',
    'Sorlug', 'Ghungash', 'Ishnok', 'Gribug', 'Skugdakh', 'Dunak', 'Trodzug',
    'Skagdug', 'Gugguh', 'Thruzdub', 'Arguh', 'Rubdig', 'Mubgagh', 'Drarguh',
    'Throdzog', 'Nubdakh', 'Surgab', 'Udmuk', 'Buznag', 'Trablag', 'Ruglug',
    'Obpug', 'Kumhosh', 'Tugzag', 'Grogblug', 'Thorbok', 'Sablag', 'Kubzurg',
    'Snudbog', 'Zabgub', 'Brublug', 'Brashog', 'Ukduh'
]
